### PR TITLE
Add foreign keys to relations table

### PR DESCRIPTION
**Pull request by arnikz**
Relates to #73.

### CODE REVIEW

**Comment by daler** [comment]
Thanks. Looks like something's funky with the travis-ci tests, likely with the docker container. I will take a look and fix.

Will need some code to detect version and warn the user when opening a db without existing FKs, and provide an upgrade path to update the db, and then some tests to verify the upgrade works.

**Comment by arnikz** [comment]
Hi @daler Did you mean to detect the sqlite version? Concerning the FKs & upgrade path we have the issue that SQLite does not support _ALTER TABLE...ADD FOREIGN KEY_ SQL construct so updating a db without existing FKs will require a new db schema + data (re)import.

**Comment by daler** [comment]
I was thinking detect gffutils database version (in the `meta` table), and upon reading the db, if it's out of date then offer to upgrade (as a one-time-per-session UserWarning). I guess the user would have to decide whether doing so is worth a complete reconstruction of the db.

The main benefit to FKs here is in avoiding user error when adding a feature manually to the features table but forgetting to put the relevant ones in the relations table, is that right? I definitely see the benefit of guaranteeing referential integrity, but the current API seems to do a good job with that (simply based on no issues or bug reports stating otherwise; not a very good metric I know).

Do you have examples of gffutils usage where having FKs would have prevented a bug? That could be used to convince users it's worth the db rebuild.

**Comment by arnikz** [comment]
Hi @daler. I agree with you. I don't have a real example (yet) where having FKs "proofed" beneficial. Nevertheless, it's a good practice to have db referential integrity in general.

**Comment by daler** [comment]
I am still on the fence about this. It's good in general to enforce referential integrity; have to work out how best to manage the notification and user communication regarding it. Closing for now, but may revisit.

**Pull request closed without merging**
