### PR TITLE
Fix major issue with merge algorithm, add new merge criteria (v0.10.1rc)

### PR DESCRIPTION
**Pull request by innovate-invent**
Sorry I didn't push this upstream sooner.
I discovered an issue with dropping the first record if it wasn't merged with the second.
This required major changes in the iteration logic.

### CODE REVIEW

**Comment by daler** [comment]
Thanks for the catch. Can you add a test that would have failed before this PR?

**Comment by innovate-invent** [comment]
No, mostly because these changes were patched in production and I don't remember the exact issues they resolved. :yum: 
I can look at creating a test in the new year, I just wanted to get you this fix with your recent pulls and release.

**Comment by daler** [comment]
OK -- as long as you're good with the existing tests that are passing, I'm fine merging this in.

**Comment by innovate-invent** [comment]
The existing tests catch everything but the edge cases I ran into.
The changes are also working in my production pipeline, I just need to capture the data that was creating the issue.

**Comment by innovate-invent** [comment]
Ah, I remember the case.
The criteria was not being applied to the first feature. If the criteria included a callback that checked the current record but not the accumulated record then it would inappropriately merge the first record while evaluating the second.

**Pull request merged**
