### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by rmzelle**
@daler, by the way, what is the default value of `merge_strategy`? Is it indicated anywhere in the docs?

### CODE REVIEW

**Comment by daler** [comment]
Thanks. Something's going on with the travis-ci testing, let me see if I can resolve it before merging.

In the signature of `create_db`, the default `merge_strategy` is `error`. Hopefully that's the path of least surprises.

**Comment by rmzelle** [comment]
Ah, I had never heard of the Signature object (https://docs.python.org/3.4/library/inspect.html#introspecting-callables-with-the-signature-object). Seems like a good thing to mention in the docs too, though! (sorry for some of these basic questions, but I dabble in a bunch of programming languages and am a master of none, and my knowledge of Python is pretty basic)

**Comment by daler** [comment]
In the Python interpreter, getting help on an object should show the signature at the top of the help. The [docs for create_db](http://daler.github.io/gffutils/autodocs/gffutils.create.create_db.html#gffutils.create.create_db) also has the signature with its defaults. This function has a ton of arguments though so it's easy to miss.

**Comment by rmzelle** [comment]
Ah, thanks, I missed those default values. I was just looking at the description for "merge_strategy".

**Pull request merged**
